remote_theme: poole/hyde
plugins:
- jekyll-remote-theme

title: Notable Figures
tagline: Informational reading about really cool people.
url: https://crxssed.dev/notable-figures
baseurl: /notable-figures/

sass:
  sass_dir: _scss
  style: :compressed
